modifyLineBreaks:
    condenseMultipleBlankLinesInto: 1
    textWrapOptions:
        columns: 80
        blocksBeginWith:
            A-Z: 1
            a-z: 1
            0-9: 0
            other: '`'