on: [push, workflow_dispatch]

jobs:
  build:
    name: AppImage build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt install qt5-default
          sudo apt install libqt5charts5 libqt5charts5-dev
          sudo apt install nlohmann-json3-dev
          sudo apt install patchelf

      - name: Build cryptopp
        run: |
          cd external-libs/cryptopp
          CXXFLAGS="-DNDEBUG -g2 -O3 -fopenmp -lgomp" make -j$(nproc) dynamic cryptest.exe
          CXXFLAGS="-DNDEBUG -g2 -O3 -fopenmp -lgomp" make -j$(nproc) libcryptopp.a libcryptopp.so cryptest.exe
          sudo make install PREFIX=/usr/local

      - name: Qmake and make
        run: |
          qmake CONFIG+=release
          make -j$(nproc)
          make install INSTALL_ROOT=appdir
          
      - name: Build AppImage
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x ./linuxdeploy-x86_64.AppImage
          chmod +x ./linuxdeploy-plugin-qt-x86_64.AppImage
          mkdir -p "appdir/usr/share/metainfo/"
          cp "me.someretical.TheoreticalDiary.appdata.xml" "appdir/usr/share/metainfo/"
          export VERSION="$(cat text/VERSION.txt)"
          export OUTPUT="TheoreticalDiary-v${VERSION}-x86_64.AppImage"
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          sudo ldconfig /usr/local/lib
          ./linuxdeploy-x86_64.AppImage --desktop-file="me.someretical.TheoreticalDiary.desktop" --icon-file="images/linux_icons/256x256/theoreticaldiary.png" --appdir="appdir" --plugin=qt --output=appimage --executable="appdir/usr/bin/theoreticaldiary"

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: theoreticaldiary-x86_64
          path: "./${OUTPUT}"
