on: [push, workflow_dispatch]

jobs:
  build:
    name: AppImage build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt install qt5-default
          sudo apt install libqt5networkauth5
          sudo apt install libqt5networkauth5-dev
          sudo apt install nlohmann-json3-dev
          sudo apt install patchelf

      - name: Build cryptopp
        run: |
          cd external-libs/cryptopp
          CXXFLAGS="-DNDEBUG -g2 -O3 -fopenmp -lgomp" make -j8 dynamic cryptest.exe
          CXXFLAGS="-DNDEBUG -g2 -O3 -fopenmp -lgomp" make -j8 libcryptopp.a libcryptopp.so cryptest.exe
          sudo make install PREFIX=/usr/local

      - name: Qmake and make
        run: |
          qmake CONFIG+=release
          make -j8
          make install INSTALL_ROOT=AppDir
          
      - name: Build AppImage
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x ./linuxdeploy-x86_64.AppImage
          chmod +x ./linuxdeploy-plugin-qt-x86_64.AppImage
          mkdir -p AppDir/usr/share/metainfo
          cp ./io.github.someretical.theoreticaldiary.appdata.xml AppDir/usr/share/metainfo/io.github.someretical.theoreticaldiary.appdata.xml
          export OUTPUT=TheoreticalDiary.AppImage
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          sudo ldconfig /usr/local/lib
          ./linuxdeploy-x86_64.AppImage -eAppDir/opt/theoreticaldiary/bin/theoreticaldiary -dio.github.someretical.theoreticaldiary.desktop -iimages/icons/hicolor/256x256/apps/theoreticaldiary.png --appdir AppDir --plugin qt --output appimage

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: theoreticaldiary-linux
          path: ./TheoreticalDiary.AppImage
