on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
      
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      
      - name: Test
        run: ls ${{GITHUB_WORKSPACE}}
        shell: cmd
