on: [push, workflow_dispatch]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Bundle build
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.6.2
        with:
          host: mac
          modules: 'qtcharts'
          extra: --external 7z
      
      - name: Build cryptopp
        run: |
          brew install llvm libomp
          cd external-libs/cryptopp
          export CXXFLAGS="-DNDEBUG -g2 -O3 -fopenmp -L/usr/local/opt/llvm/lib -I/usr/local/opt/llvm/include"
          export CC="/usr/local/opt/llvm/bin/clang"
          export CXX="/usr/local/opt/llvm/bin/clang++"
          make -j$(sysctl -n hw.logicalcpu) dynamic cryptest.exe
          make -j$(sysctl -n hw.logicalcpu) libcryptopp.a libcryptopp.so cryptest.exe
          sudo make install PREFIX=/usr/local

      - name: qmake and make
        run: |
          sudo xcode-select -s /Applications/Xcode_12.1.1.app/Contents/Developer
          qmake QMAKE_CC="/usr/local/opt/llvm/bin/clang" QMAKE_CXX="/usr/local/opt/llvm/bin/clang++" CONFIG+=release QMAKE_LIBS+="-L/usr/local/opt/llvm/lib -L/usr/local/lib" INCLUDEPATH+="-I/usr/local/opt/llvm/include"
          make -j$(sysctl -n hw.logicalcpu)
          
      - name: macdeployqt
        id: macdeploy
        run: |
          export FULL_NAME="TheoreticalDiary-v$(cat text/VERSION.txt)-x86_64.app"
          echo ::set-output name=full_name::${FULL_NAME}
          macdeployqt TheoreticalDiary.app -verbose=2

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: ${{steps.macdeploy.outputs.full_name}}
          path: TheoreticalDiary.app
