on: [push, workflow_dispatch]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Shared build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.6.2
        with:
          host: windows
          modules: 'qtcharts'
          extra: --external 7z
      
      - name: Build cryptopp
        run: |
          cd external-libs/cryptopp 
          nmake /f cryptest.nmake CXXFLAGS="/DNDEBUG /D_NDEBUG /Oi /Oy /O3 /MD /openmp"

      - name: qmake and nmake
        run: |
          qmake theoreticaldiary.pro CONFIG+=release
          nmake qmake_all
          nmake
          nmake clean

      - name: Link DLLs
        run: windeployqt release/theoreticaldiary.exe --compiler-runtime

      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: theoreticaldiary-x86_64
          path: release
